server:
  port: 8000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/appointmentscheduler
    username: root
    password: SAM1@navale
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: navalesomnath1@gmail.com
    password: avqsqwvxndvqoalj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  jwt_secret: 47adc5936b429f0fe67b70c83dc309d7e34cc6426007358ec121d28043a4f993

